# Generated by Django 3.1.7 on 2021-06-08 17:34

import LoVisto.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=128)),
                ('password', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=512)),
                ('link', models.CharField(default='', max_length=1024)),
                ('description', models.TextField(default='')),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('num_comment', models.IntegerField(default=0)),
                ('extended_info', models.TextField(default='')),
                ('user', models.ForeignKey(default=LoVisto.models.User, on_delete=django.db.models.deletion.CASCADE, to='LoVisto.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoVisto.content')),
                ('user', models.ForeignKey(default=LoVisto.models.User, on_delete=django.db.models.deletion.CASCADE, to='LoVisto.user')),
            ],
        ),
    ]
