# Generated by Django 3.1.7 on 2021-06-08 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoVisto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
