# Generated by Django 3.1.7 on 2021-06-08 20:23

import LoVisto.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoVisto', '0002_auto_20210608_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoVisto.content')),
                ('user', models.ForeignKey(default=LoVisto.models.User, on_delete=django.db.models.deletion.CASCADE, to='LoVisto.user')),
            ],
        ),
    ]
