# Generated by Django 3.1.7 on 2021-05-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoVisto', '0003_auto_20210530_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='source',
        ),
    ]
