# Generated by Django 3.1.7 on 2021-07-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoVisto', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(default='css/LoVisto/style.css', max_length=128),
        ),
    ]
