# Generated by Django 3.1.7 on 2021-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoVisto', '0004_remove_content_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='content',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
