# Generated by Django 3.1.7 on 2021-05-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoVisto', '0005_auto_20210530_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
    ]
