# Generated by Django 3.1.7 on 2021-05-30 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LoVisto', '0006_auto_20210530_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='extended_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='num_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='positive',
            field=models.IntegerField(default=0),
        ),
    ]
