# Generated by Django 3.1.7 on 2021-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoVisto', '0007_auto_20210530_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
