# Generated by Django 3.1.7 on 2021-05-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoVisto', '0009_auto_20210530_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='user_name',
        ),
    ]
